project:
  type: website
  resources:
    - "resources"
    - "posts"
    - "projects"
  output-dir: docs


# https://icon-sets.iconify.design/ion/?icon-filter=social
website:
  back-to-top-navigation: true
  page-navigation: true
  bread-crumbs: true
  open-graph: true 
  title: "Thomas Lavigne, PhD"
  image: resources/images/profile_pic2.jpeg
  favicon: resources/images/profile_pic2.jpeg
  description: "Thomas Lavigne, PhD in biomechanics (biomécanique), specialized in vascular mechanics, poromechanics, hydrogels, and numerical simulation (fenics and fenicsx). Personal research webpage presenting projects in FEniCSx, Gmsh, porous media modeling, publications, CV, and post-doctoral work at ENS Paris-Saclay, I2M Bordeaux, Université du Luxembourg, LMS Polytechnique, and the IBHGC laboratory at ENSAM Paris."
  site-url: https://th0maslavigne.github.io/
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: news.qmd
        text: News 
      - text: Research
        menu:
          - href: projects.qmd
            text: Projects
          - href: publications.qmd
            text: Publications & Outreach
          - href: talks.qmd
            text: Talks
      - text: Academia
        menu:
          - href: teaching.qmd
            text: Teaching & Supervision
          - href: education.qmd
            text: Academic & Research Appointments
      - text: CV
        menu:
        - text: Academic CV
          href: resources/documents/cv/thomas_lavigne_cv_2.pdf
        - text: Narrative CV (2025)
          href: resources/documents/cv/Narrative_CV_Lavigne.pdf
        target: _blank
      - text: "{{< iconify ion:logo-github >}}"
        href: https://github.com/Th0masLavigne
      - text: "{{< iconify ion:flame-sharp >}}"
        href: https://th0maslavigne.github.io/FEniCSx_GMSH_tutorials/README.html
  page-footer: 
    right: |
      <ul style="list-style-type: none; padding: 0; margin: 0;">
        <li>📍 <a href="https://lms.ip-paris.fr">Laboratoire de Mécanique des Solides</a> </li>
        <li>📧 <a href="mailto:thomas.lavigne@polytechnique.edu">thomas.lavigne@polytechnique.edu</a></li>
      </ul>

    center:
      - icon: github
        href: https://github.com/Th0masLavigne
      - icon: twitter
        href: https://x.com/Thomas_Lavigne_
      - icon: linkedin
        href: https://www.linkedin.com/in/thomas-l-7a6608109/
      - text: "{{< iconify fa-brands:orcid >}}"
        href: https://orcid.org/0000-0003-2690-3542
      - icon: mortarboard
        href: https://scholar.google.com/citations?user=FYXQf_UAAAAJ
      - text: "{{< iconify simple-icons:researchgate >}}"
        href: https://www.researchgate.net/profile/Thomas-Lavigne-2

    left: |
      <small>
        &copy; 2025 Thomas Lavigne — All rights reserved.<br>
        <a href="https://quarto.org/">Built with Quarto</a>
      </small>


# https://quarto.org/docs/output-formats/html-themes.html
format:
  html:
    email-obfuscation: javascript
    theme:
      light: [flatly,resources/style_css_files/style_site.scss]
      dark: [darkly,resources/style_css_files/style_site_dark.scss]
    respect-user-color-scheme: false
    css: resources/style_css_files/styles.css
    toc: true
    smooth-scroll: true
#     include-after-body:
#       text: |
#         <script type="application/javascript" src="resources/style_css_files/custom_hal.js"></script>
#         <script type="application/javascript" src="resources/style_css_files/carousel.js"></script>

# header-includes:
#   - <script src="resources/style_css_files/carousel.js"></script>